Syntax error in schema file should point to error
Summary:
When we have a syntax error in a bit of SQL, we generally get back an error
that's only partly useful; something like

    Error: pq: syntax error at or near "BREATE"

The underlying error from `pq` has the byte position in the query which we can
use to compute the line and column (assuming we have the query) and get this:

    Error: pq: syntax error at or near "BREATE" (at byte 674: line 26, col 4):
    BREATE TABLE artifacts (

Test Plan: Manual

Reviewers: dp

Reviewed By: dp

Differential Revision: https://ph0.b10e.net/D705